### ISSUE TITLE
Epic: WIT Website Build Tasks

### ISSUE THREAD

**Issue by dinaluciano** [sarahetoms/WIT-Penn#16]
Determine Next Steps for the following.  Some may need a dedicated ticket.  

- [ ] Dev Site Instructions and Knowledge Sharing
- [x] Site Map Approval 
- [x] Site Theme/Visual Assets
- [ ] Written Content Needed
- [ ] Visual Assets Needed
- [ ] Directory - Next Steps
- [ ] Resource Links - Next Steps
- [ ] Blog/Articles - Next Steps
- [ ] Social Media integration - Next Steps

**Comment by dinaluciano** [comment]
--- Pantheon and Wordpress (closed group/link) 
---Set time with Liz for learning how to update/ determine visual assets
---Consider site map approved (one more request) 
---Develop a concrete list of what we need to write/ draft text for approval
---Content: smaller team draft mission/goals, etc.  
     -- Mission Statement:  
     -- About
---Directory - how many responses?  8/100?   Encourage submissions in slack
---Resource links: encourage in slack
---Skills Matrix (Know/Want to Know)

**Comment by dinaluciano** [comment]
Meeting on July 17th
--Liz Lennox
--Taylor Kahny
--Joanne Wells
--Dina Luciano

We will create tickets against this epic to move forward
